phone_params = {
    "client_input_params": {
        "device_id": "android-5d6970bfe16daaa1",
        "family_device_id": "af9cda5c-8cb2-46bf-8cd3-f3a524a0e812",
        "lois_settings": {"lois_token": "", "lara_override": ""},
        "was_headers_prefill_available": 0,
        "whatsapp_installed_on_client": 0,
        "auto_conf_client_start_msgs": {"0": ""},
        "accounts_list": [],
        "confirmed_cp_and_code": {},
        "fb_ig_device_id": [],
        "phone": "+46739306497",
        "was_headers_prefill_used": 0,
        "headers_infra_flow_id": "",
        "build_type": "release",
        "encrypted_msisdn": ""
    },
    "server_params": {
        "is_from_logged_out": 0,
        "device_id": "android-5d6970bfe16daaa1",
        "waterfall_id": "d9f5d9d0-5416-45c2-bf64-f9369da6ffff",
        "flow_info": "{\"flow_name\":\"new_to_family_ig_f3_order\",\"flow_type\":\"ntf\"}",
        "is_platform_login": 0,
        "family_device_id": "af9cda5c-8cb2-46bf-8cd3-f3a524a0e812",
        "reg_info": "{\"first_name\":null,\"last_name\":null,\"full_name\":null,\"contactpoint\":null,\"contactpoint_type\":null,\"is_cp_auto_confirmed\":false,\"confirmation_code\":null,\"birthday\":null,\"did_use_age\":null,\"gender\":null,\"use_custom_gender\":false,\"custom_gender\":null,\"encrypted_password\":null,\"username\":null,\"username_prefill\":null,\"fb_conf_source\":null,\"device_id\":\"android-5d6970bfe16daaa1\",\"ig4a_qe_device_id\":null,\"family_device_id\":\"af9cda5c-8cb2-46bf-8cd3-f3a524a0e812\",\"nta_eligibility_reason\":null,\"ig_nta_test_group\":null,\"user_id\":null,\"safetynet_token\":null,\"safetynet_response\":null,\"machine_id\":null,\"profile_photo\":null,\"profile_photo_id\":null,\"profile_photo_upload_id\":null,\"avatar\":null,\"email_oauth_token\":null,\"encrypted_msisdn\":null,\"encrypted_msisdn_for_safetynet\":null,\"reached_from_headers_safetynet\":null,\"headers_last_infra_flow_id\":null,\"headers_last_infra_flow_id_safetynet\":null,\"headers_flow_id\":null,\"sso_enabled\":null,\"existing_accounts\":null,\"used_ig_birthday\":null,\"sync_info\":null,\"create_new_to_app_account\":null,\"skip_session_info\":null,\"ck_error\":null,\"ck_id\":null,\"ck_nonce\":null,\"should_save_password\":null,\"horizon_synced_username\":null,\"fb_access_token\":null,\"horizon_synced_profile_pic\":null,\"is_identity_synced\":false,\"is_msplit_reg\":null,\"user_id_of_msplit_creator\":null,\"dma_data_combination_consent_given\":null,\"xapp_accounts\":null,\"fb_device_id\":null,\"fb_machine_id\":null,\"ig_device_id\":null,\"ig_machine_id\":null,\"should_skip_nta_upsell\":null,\"big_blue_token\":null,\"skip_sync_step_nta\":null,\"caa_reg_flow_source\":\"login_home_native_integration_point\",\"ig_authorization_token\":null,\"full_sheet_flow\":false,\"crypted_user_id\":null,\"is_caa_perf_enabled\":true,\"is_preform\":true,\"ignore_suma_check\":false,\"ignore_existing_login\":false,\"ignore_existing_login_from_suma\":false,\"ignore_existing_login_after_errors\":false,\"suggested_first_name\":null,\"suggested_last_name\":null,\"suggested_full_name\":null,\"frl_authorization_token\":null,\"post_form_errors\":null,\"skip_step_without_errors\":false,\"existing_account_exact_match_checked\":false,\"existing_account_fuzzy_match_checked\":false,\"confirmation_code_send_error\":null,\"is_too_young\":false,\"source_account_type\":null,\"whatsapp_installed_on_client\":false,\"confirmation_medium\":null,\"source_credentials_type\":null,\"source_cuid\":null,\"source_account_reg_info\":null,\"soap_creation_source\":null,\"source_account_type_to_reg_info\":null,\"registration_flow_id\":\"c50f9583-7d41-4581-85ef-47efc532e2e6\",\"should_skip_youth_tos\":false,\"is_youth_regulation_flow_complete\":false,\"is_on_cold_start\":false,\"email_oauth_exists\":false,\"email_prefilled\":false,\"cp_confirmed_by_auto_conf\":false,\"auto_conf_info\":null,\"in_sowa_experiment\":false,\"youth_regulation_config\":null,\"flash_call_permissions_status\":null,\"attestation_result\":null,\"request_data_and_challenge_nonce_string\":null,\"confirmed_cp_and_code\":null}",
        "offline_experiment_group": "caa_iteration_v3_perf_ig_4",
        "cp_funnel": 0,
        "INTERNAL_INFRA_THEME": "default",

        "cp_source": 0,
        "event_request_id": "4c7cfa62-62c2-4c57-8ec4-3d152107de0c",
        "INTERNAL__latency_qpl_instance_id": 107933879200033,
        "INTERNAL__latency_qpl_marker_id": 36707139,

        "is_from_logged_in_switcher": 0,
        "qe_device_id": "3aada630-7663-40b1-8dee-5089b8437ac4",
        "current_step": 0,
    }
}

phone_reg_info = {'first_name': None, 'last_name': None, 'full_name': None, 'contactpoint': None,
                  'contactpoint_type': None, 'is_cp_auto_confirmed': False, 'confirmation_code': None, 'birthday': None,
                  'did_use_age': None, 'gender': None, 'use_custom_gender': False, 'custom_gender': None,
                  'encrypted_password': None, 'username': None, 'username_prefill': None, 'fb_conf_source': None,
                  'device_id': 'android-5d6970bfe16daaa1', 'ig4a_qe_device_id': None,
                  'family_device_id': 'af9cda5c-8cb2-46bf-8cd3-f3a524a0e812', 'nta_eligibility_reason': None,
                  'ig_nta_test_group': None, 'user_id': None, 'safetynet_token': None, 'safetynet_response': None,
                  'machine_id': None, 'profile_photo': None, 'profile_photo_id': None, 'profile_photo_upload_id': None,
                  'avatar': None, 'email_oauth_token': None, 'encrypted_msisdn': None,
                  'encrypted_msisdn_for_safetynet': None, 'reached_from_headers_safetynet': None,
                  'headers_last_infra_flow_id': None, 'headers_last_infra_flow_id_safetynet': None,
                  'headers_flow_id': None, 'sso_enabled': None, 'existing_accounts': None, 'used_ig_birthday': None,
                  'sync_info': None, 'create_new_to_app_account': None, 'skip_session_info': None, 'ck_error': None,
                  'ck_id': None, 'ck_nonce': None, 'should_save_password': None, 'horizon_synced_username': None,
                  'fb_access_token': None, 'horizon_synced_profile_pic': None, 'is_identity_synced': False,
                  'is_msplit_reg': None, 'user_id_of_msplit_creator': None, 'dma_data_combination_consent_given': None,
                  'xapp_accounts': None, 'fb_device_id': None, 'fb_machine_id': None, 'ig_device_id': None,
                  'ig_machine_id': None, 'should_skip_nta_upsell': None, 'big_blue_token': None,
                  'skip_sync_step_nta': None, 'caa_reg_flow_source': 'login_home_native_integration_point',
                  'ig_authorization_token': None, 'full_sheet_flow': False, 'crypted_user_id': None,
                  'is_caa_perf_enabled': True, 'is_preform': True, 'ignore_suma_check': False,
                  'ignore_existing_login': False, 'ignore_existing_login_from_suma': False,
                  'ignore_existing_login_after_errors': False, 'suggested_first_name': None,
                  'suggested_last_name': None, 'suggested_full_name': None, 'frl_authorization_token': None,
                  'post_form_errors': None, 'skip_step_without_errors': False,
                  'existing_account_exact_match_checked': False, 'existing_account_fuzzy_match_checked': False,
                  'confirmation_code_send_error': None, 'is_too_young': False, 'source_account_type': None,
                  'whatsapp_installed_on_client': False, 'confirmation_medium': None, 'source_credentials_type': None,
                  'source_cuid': None, 'source_account_reg_info': None, 'soap_creation_source': None,
                  'source_account_type_to_reg_info': None,
                  'registration_flow_id': 'c50f9583-7d41-4581-85ef-47efc532e2e6', 'should_skip_youth_tos': False,
                  'is_youth_regulation_flow_complete': False, 'is_on_cold_start': False, 'email_oauth_exists': False,
                  'email_prefilled': False, 'cp_confirmed_by_auto_conf': False, 'auto_conf_info': None,
                  'in_sowa_experiment': False, 'youth_regulation_config': None, 'flash_call_permissions_status': None,
                  'attestation_result': None, 'request_data_and_challenge_nonce_string': None,
                  'confirmed_cp_and_code': None}
